# Generated by Django 3.1.4 on 2020-12-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPhoto',
        ),
    ]
