# Generated by Django 3.1.4 on 2020-12-15 11:13

import branch.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_delete_productphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=branch.models.get_path_upload_image, verbose_name='Фото продукции')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.product', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Фотографии к продукции',
                'verbose_name_plural': 'Фотографии к продукции',
            },
        ),
    ]
