# Generated by Django 3.1.5 on 2021-03-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='short_description',
            field=models.CharField(default='', max_length=500, verbose_name='Краткое описание'),
        ),
    ]
